### ISSUE TITLE
New term request: PTM localization

### ISSUE THREAD

**Issue by magnuspalmblad** [edamontology/edamontology#231] opened 2016-10-07 12:08 UTC
PTM localization

Could be under PTM identification
"PTM localization" is_a "PTM identification", i.e. it is more specific and implies the type of PTM is known

or on the same level (sibling) to "PTM identification". Sometimes, one may be able to localize a PTM but only know its mass. There are some PTMs with the same (exact) mass, e.g. hexoses. Other PTM pairs have similar masses that may not be distinguishable on low-resolution instruments.

Theoretically, I prefer the latter, though most actual tools probably assume the type of modification before trying to localize it (or assumes whatever was looked for in the peptide identification).

**Comment by veitveit** [comment] 2016-10-11 19:24
Duplicate of #187

**Closed** 2016-11-01 04:16 UTC
Labels: done - staged for release
